# Generated by Django 6.0.6 on 2026-06-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('rejected', 'رد شده'), ('canceled', 'لغو شده'), ('completed', 'انجام شده')], default='pending', max_length=20, verbose_name='وضعیت رزرو')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('refunded', 'برگشت داده شده')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('price_at_booking', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت در زمان رزرو')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ رزرو')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('canceled_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('customer_note', models.TextField(blank=True, null=True, verbose_name='یادداشت مشتری')),
                ('provider_note', models.TextField(blank=True, null=True, verbose_name='یادداشت ارائه\u200cدهنده')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_customer', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('provider', models.ForeignKey(limit_choices_to={'role': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_provider', to=settings.AUTH_USER_MODEL, verbose_name='ارائه\u200cدهنده')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service', verbose_name='سرویس')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='services.timeslot', verbose_name='بازه زمانی')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='شماره تراکنش')),
                ('is_successful', models.BooleanField(default=False, verbose_name='موفق')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='bookings_bo_custome_0cbf77_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', 'status'], name='bookings_bo_provide_c56754_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service', 'status'], name='bookings_bo_service_b2b755_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='bookings_bo_booking_f34616_idx'),
        ),
    ]
