# Generated by Django 6.0.6 on 2026-06-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام دارنده کارت'),
        ),
    ]
